/**
 * Generates the complete DNS record set for the platform domain.
 *
 *   npm run dns
 *
 * Pulls the live sending records from Resend and combines them with the hosting
 * and inbound-mail records, emitting:
 *
 *   docs/dns/<domain>.zone   BIND file — import in one action, no retyping
 *   docs/dns/README.md       the same records as a table, with the traps called out
 *
 * Why a generator rather than a static list: Resend returns record NAMES relative
 * to the registrable domain (`send.digits`), while the Cloudflare zone is the
 * subdomain itself (`digits.dpdns.org`). Pasting Resend's names verbatim yields
 * `send.digits.digits.dpdns.org`, which never verifies and gives no error — the
 * domain just sits at "not_started". Everything below is emitted fully qualified
 * so the relative-name question cannot arise.
 */
import fs from "node:fs/promises";
import path from "node:path";
import { loadEnv, ROOT } from "./supabase-admin.mjs";

const { env } = await loadEnv();

const SITE = (env.VITE_SITE_URL ?? env.PUBLIC_SITE_URL ?? "")
  .replace(/^https?:\/\//, "")
  .replace(/\/$/, "");
if (!SITE) {
  console.error("Set VITE_SITE_URL in .env first.");
  process.exit(1);
}

const PAGES_TARGET = process.env.PAGES_TARGET ?? "yakyakyak14.github.io";
const FORWARD_TO = process.env.FORWARD_TO ?? "yakyakyak1414@gmail.com";

const resendKey = env.RESEND_API_KEY;
if (!resendKey) {
  console.error("RESEND_API_KEY is not set.");
  process.exit(1);
}

// ------------------------------------------------------------------ Resend
const list = await fetch("https://api.resend.com/domains", {
  headers: { Authorization: `Bearer ${resendKey}` },
}).then((r) => r.json());

if (list?.name === "restricted_api_key") {
  console.error("RESEND_API_KEY is send-only; it cannot read domain records.");
  process.exit(1);
}

const domain = (list.data ?? []).find((d) => d.name === SITE);
if (!domain) {
  console.error(`${SITE} is not registered in Resend. Add it first.`);
  process.exit(1);
}

const detail = await fetch(`https://api.resend.com/domains/${domain.id}`, {
  headers: { Authorization: `Bearer ${resendKey}` },
}).then((r) => r.json());

/**
 * Resend names are relative to the registrable domain. Convert to an absolute
 * name so it is unambiguous regardless of which zone it is pasted into.
 */
function absolute(name) {
  const clean = String(name).replace(/\.$/, "");
  if (clean === "@" || clean === "") return `${SITE}.`;
  if (clean.endsWith(SITE)) return `${clean}.`;

  // e.g. "send.digits" inside zone "digits.dpdns.org" -> "send.digits.dpdns.org."
  const label = SITE.split(".")[0];
  if (clean === label) return `${SITE}.`;
  if (clean.endsWith(`.${label}`)) return `${clean.slice(0, -label.length - 1)}.${SITE}.`;
  return `${clean}.${SITE}.`;
}

const sending = (detail.records ?? []).map((r) => ({
  purpose: r.record === "DKIM" ? "Resend DKIM" : "Resend SPF",
  type: r.type,
  name: absolute(r.name),
  value: r.value,
  priority: r.priority ?? null,
}));

// ------------------------------------------------------- hosting + inbound
const hosting = [
  {
    purpose: "GitHub Pages",
    type: "CNAME",
    name: `${SITE}.`,
    value: `${PAGES_TARGET}.`,
    priority: null,
  },
];

const inbound = [
  {
    purpose: "Cloudflare Email Routing",
    type: "MX",
    name: `${SITE}.`,
    value: "route1.mx.cloudflare.net.",
    priority: 2,
  },
  {
    purpose: "Cloudflare Email Routing",
    type: "MX",
    name: `${SITE}.`,
    value: "route2.mx.cloudflare.net.",
    priority: 21,
  },
  {
    purpose: "Cloudflare Email Routing",
    type: "MX",
    name: `${SITE}.`,
    value: "route3.mx.cloudflare.net.",
    priority: 31,
  },
  {
    purpose: "Cloudflare Email Routing",
    type: "TXT",
    name: `${SITE}.`,
    value: "v=spf1 include:_spf.mx.cloudflare.net include:amazonses.com ~all",
    priority: null,
  },
  {
    purpose: "DMARC",
    type: "TXT",
    name: `_dmarc.${SITE}.`,
    value: "v=DMARC1; p=none;",
    priority: null,
  },
];

const all = [...hosting, ...sending, ...inbound];

// ------------------------------------------------------------- zone file
/*
 * MX and CNAME targets must be fully qualified in a zone file. Without the
 * trailing dot BIND treats them as relative, so "…amazonses.com" silently
 * becomes "…amazonses.com.digits.dpdns.org" and mail never leaves.
 */
const quote = (v, type) => {
  if (type === "TXT") return `"${v.replace(/"/g, '\\"')}"`;
  if (type === "MX" || type === "CNAME") return v.endsWith(".") ? v : `${v}.`;
  return v;
};

const zone = `; DNS for ${SITE}
; Generated by scripts/dns-records.mjs — do not edit by hand.
;
; Import in Cloudflare: DNS -> Records -> Import and Export -> Import.
; Every name is fully qualified, so it is correct whether the zone is
; ${SITE} or its parent.
;
; Set the CNAME below to "DNS only" (grey cloud) until GitHub has issued the
; certificate, otherwise the ACME challenge cannot complete.

${all
  .map((r) => {
    const label = `; ${r.purpose}`;
    const rdata =
      r.priority !== null ? `${r.priority} ${quote(r.value, r.type)}` : quote(r.value, r.type);
    return `${label}\n${r.name.padEnd(42)} 1 IN ${r.type.padEnd(6)} ${rdata}`;
  })
  .join("\n\n")}
`;

// ----------------------------------------------------------------- markdown
const table = [
  "| Purpose | Type | Name | Value | Priority |",
  "| --- | --- | --- | --- | --- |",
  ...all.map(
    (r) =>
      `| ${r.purpose} | ${r.type} | \`${r.name.replace(/\.$/, "")}\` | \`${
        r.value.length > 60 ? `${r.value.slice(0, 57)}…` : r.value
      }\` | ${r.priority ?? "—"} |`,
  ),
].join("\n");

const readme = `# DNS records for ${SITE}

Generated by \`npm run dns\` from the live Resend configuration. Regenerate rather
than editing — the DKIM key changes if the domain is re-added in Resend.

**Fastest path:** Cloudflare → DNS → Records → **Import and Export → Import** →
upload \`${SITE}.zone\`. Every name in it is fully qualified, so nothing depends on
which zone it lands in.

${table}

## Three things that will silently break this

**1. Resend's record names are relative to \`dpdns.org\`, not to \`${SITE}\`.**
The dashboard shows \`send.digits\` and \`resend._domainkey.digits\`. Typed into a
\`${SITE}\` zone as-is, those become \`send.digits.${SITE}\`. Nothing errors — the
domain simply stays at *not_started* forever. The generated records above are
already absolute, which removes the question.

**2. You get one set of MX records, so pick one inbound provider.**
The table uses **Cloudflare Email Routing**, which forwards \`info@${SITE}\` to
\`${FORWARD_TO}\` with no code. Resend's *Enable Receiving* wants its own MX
(\`inbound-smtp…amazonses.com\`) and delivers over a webhook rather than to a
mailbox — it cannot forward to Gmail on its own. **Turn Resend's receiving toggle
off** so the two do not compete.

The SPF record above already includes both \`_spf.mx.cloudflare.net\` and
\`amazonses.com\`, so receiving through Cloudflare and sending through Resend
coexist correctly.

**3. An apex CNAME alongside MX is only legal because of Cloudflare.**
\`${SITE}\` carries both a CNAME (to GitHub Pages) and MX records. Standard DNS
forbids that. Cloudflare's CNAME flattening makes it work by answering with A
records. On a DNS host without flattening, swap the CNAME for GitHub's four A
records.

## After importing

1. Cloudflare → **Email → Email Routing → Enable**, then create the address
   \`info@${SITE}\` → \`${FORWARD_TO}\` and click the confirmation link Cloudflare
   sends to that inbox. The route stays inactive until you do.
2. GitHub repo → **Settings → Pages → Custom domain** → \`${SITE}\`, then enable
   **Enforce HTTPS** once the certificate is issued.
3. Wait for Resend to report **Verified**, then switch the sender:

   \`\`\`bash
   # .env
   EMAIL_FROM="DIGITs Election Watch <info@${SITE}>"
   npm run fn:deploy -- --secrets
   \`\`\`

   Do not switch it before Resend verifies — an unverified sender returns 403 and
   no DIGEO email goes out at all.

## Verify

\`\`\`bash
curl -I https://${SITE}                      # 200
nslookup -type=MX ${SITE}                    # three Cloudflare MX
nslookup -type=TXT resend._domainkey.${SITE} # the DKIM key
npm run dns:check                            # re-reads Resend's status
\`\`\`
`;

const outDir = path.join(ROOT, "docs/dns");
await fs.mkdir(outDir, { recursive: true });
await fs.writeFile(path.join(outDir, `${SITE}.zone`), zone, "utf8");
await fs.writeFile(path.join(outDir, "README.md"), readme, "utf8");

console.log(`Resend domain status : ${detail.status}`);
console.log(`Records emitted      : ${all.length}`);
console.log(
  `  hosting  ${hosting.length}   sending  ${sending.length}   inbound  ${inbound.length}`,
);
console.log(`\nWrote docs/dns/${SITE}.zone and docs/dns/README.md`);
