/**
 * Regenerates public/robots.txt and public/sitemap.xml from the configured site
 * URL, so they can never drift from the domain the app actually serves on.
 *
 *   npm run seo                                  # uses VITE_SITE_URL from .env
 *   npm run seo -- https://digits-ng.dpdns.org   # or an explicit URL
 */
import fs from "node:fs/promises";
import path from "node:path";
import { loadEnv, ROOT } from "./supabase-admin.mjs";

const FALLBACK = "https://digits-election-watch.vercel.app";

const { env } = await loadEnv();
const argUrl = process.argv.slice(2).find((a) => !a.startsWith("--"));
const raw = argUrl ?? env.VITE_SITE_URL ?? env.PUBLIC_SITE_URL ?? FALLBACK;
const SITE = (/^https?:\/\//.test(raw) ? raw : `https://${raw}`).replace(/\/+$/, "");

/** Public pages only. Anything holding evidence or identity stays out of the index. */
const PAGES = [
  ["/", "daily", "1.0"],
  ["/live", "hourly", "0.9"],
  ["/i-witness", "hourly", "0.9"],
  ["/get-involved", "weekly", "0.8"],
  ["/features", "monthly", "0.7"],
  ["/how-it-works", "monthly", "0.7"],
  ["/about", "monthly", "0.6"],
  ["/contact", "monthly", "0.5"],
];

const robots = `# DIGITs Nigeria Election Watch — citizen election observation platform
# Public pages are open to crawlers. The Command Center and personal account
# areas are not: they hold evidence and identity data.
#
# Generated by scripts/generate-seo.mjs — edit that, not this file.

User-agent: *
Allow: /
${PAGES.filter(([p]) => p !== "/")
  .map(([p]) => `Allow: ${p}`)
  .join("\n")}
Disallow: /control-center
Disallow: /account
Disallow: /auth

Sitemap: ${SITE}/sitemap.xml
`;

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-seo.mjs — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${PAGES.map(
  ([page, changefreq, priority]) => `  <url>
    <loc>${SITE}${page === "/" ? "/" : page}</loc>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`,
).join("\n")}
</urlset>
`;

await fs.writeFile(path.join(ROOT, "public/robots.txt"), robots, "utf8");
await fs.writeFile(path.join(ROOT, "public/sitemap.xml"), sitemap, "utf8");

console.log(`Site URL: ${SITE}`);
console.log("Wrote public/robots.txt and public/sitemap.xml");
