/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LiveRouteImport } from './routes/live'
import { Route as AuthenticatedControlCenterRouteImport } from './routes/_authenticated/control-center'
import { Route as AuthenticatedControlCenterIndexRouteImport } from './routes/_authenticated/control-center/index'
import { Route as AuthenticatedControlCenterLiveRouteImport } from './routes/_authenticated/control-center/live'
import { Route as AuthenticatedControlCenterObserversRouteImport } from './routes/_authenticated/control-center/observers'
import { Route as AuthenticatedControlCenterPublicRouteImport } from './routes/_authenticated/control-center/public'
import { Route as AuthenticatedControlCenterReportsRouteImport } from './routes/_authenticated/control-center/reports'
import { Route as AuthenticatedControlCenterSettingsRouteImport } from './routes/_authenticated/control-center/settings'
import { Route as AuthenticatedControlCenterTrainingRouteImport } from './routes/_authenticated/control-center/training'
import { Route as AuthenticatedControlCenterUsersRouteImport } from './routes/_authenticated/control-center/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedControlCenterRoute =
  AuthenticatedControlCenterRouteImport.update({
    id: '/control-center',
    path: '/control-center',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedControlCenterIndexRoute =
  AuthenticatedControlCenterIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedControlCenterRoute,
  } as any)
const AuthenticatedControlCenterLiveRoute =
  AuthenticatedControlCenterLiveRouteImport.update({
    id: '/live',
    path: '/live',
    getParentRoute: () => AuthenticatedControlCenterRoute,
  } as any)
const AuthenticatedControlCenterObserversRoute =
  AuthenticatedControlCenterObserversRouteImport.update({
    id: '/observers',
    path: '/observers',
    getParentRoute: () => AuthenticatedControlCenterRoute,
  } as any)
const AuthenticatedControlCenterPublicRoute =
  AuthenticatedControlCenterPublicRouteImport.update({
    id: '/public',
    path: '/public',
    getParentRoute: () => AuthenticatedControlCenterRoute,
  } as any)
const AuthenticatedControlCenterReportsRoute =
  AuthenticatedControlCenterReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedControlCenterRoute,
  } as any)
const AuthenticatedControlCenterSettingsRoute =
  AuthenticatedControlCenterSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedControlCenterRoute,
  } as any)
const AuthenticatedControlCenterTrainingRoute =
  AuthenticatedControlCenterTrainingRouteImport.update({
    id: '/training',
    path: '/training',
    getParentRoute: () => AuthenticatedControlCenterRoute,
  } as any)
const AuthenticatedControlCenterUsersRoute =
  AuthenticatedControlCenterUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedControlCenterRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/get-involved': typeof GetInvolvedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/live': typeof LiveRoute
  '/control-center': typeof AuthenticatedControlCenterRouteWithChildren
  '/control-center/live': typeof AuthenticatedControlCenterLiveRoute
  '/control-center/observers': typeof AuthenticatedControlCenterObserversRoute
  '/control-center/public': typeof AuthenticatedControlCenterPublicRoute
  '/control-center/reports': typeof AuthenticatedControlCenterReportsRoute
  '/control-center/settings': typeof AuthenticatedControlCenterSettingsRoute
  '/control-center/training': typeof AuthenticatedControlCenterTrainingRoute
  '/control-center/users': typeof AuthenticatedControlCenterUsersRoute
  '/control-center/': typeof AuthenticatedControlCenterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/get-involved': typeof GetInvolvedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/live': typeof LiveRoute
  '/control-center/live': typeof AuthenticatedControlCenterLiveRoute
  '/control-center/observers': typeof AuthenticatedControlCenterObserversRoute
  '/control-center/public': typeof AuthenticatedControlCenterPublicRoute
  '/control-center/reports': typeof AuthenticatedControlCenterReportsRoute
  '/control-center/settings': typeof AuthenticatedControlCenterSettingsRoute
  '/control-center/training': typeof AuthenticatedControlCenterTrainingRoute
  '/control-center/users': typeof AuthenticatedControlCenterUsersRoute
  '/control-center': typeof AuthenticatedControlCenterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/get-involved': typeof GetInvolvedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/live': typeof LiveRoute
  '/_authenticated/control-center': typeof AuthenticatedControlCenterRouteWithChildren
  '/_authenticated/control-center/live': typeof AuthenticatedControlCenterLiveRoute
  '/_authenticated/control-center/observers': typeof AuthenticatedControlCenterObserversRoute
  '/_authenticated/control-center/public': typeof AuthenticatedControlCenterPublicRoute
  '/_authenticated/control-center/reports': typeof AuthenticatedControlCenterReportsRoute
  '/_authenticated/control-center/settings': typeof AuthenticatedControlCenterSettingsRoute
  '/_authenticated/control-center/training': typeof AuthenticatedControlCenterTrainingRoute
  '/_authenticated/control-center/users': typeof AuthenticatedControlCenterUsersRoute
  '/_authenticated/control-center/': typeof AuthenticatedControlCenterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/features'
    | '/get-involved'
    | '/how-it-works'
    | '/live'
    | '/control-center'
    | '/control-center/live'
    | '/control-center/observers'
    | '/control-center/public'
    | '/control-center/reports'
    | '/control-center/settings'
    | '/control-center/training'
    | '/control-center/users'
    | '/control-center/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/features'
    | '/get-involved'
    | '/how-it-works'
    | '/live'
    | '/control-center/live'
    | '/control-center/observers'
    | '/control-center/public'
    | '/control-center/reports'
    | '/control-center/settings'
    | '/control-center/training'
    | '/control-center/users'
    | '/control-center'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/features'
    | '/get-involved'
    | '/how-it-works'
    | '/live'
    | '/_authenticated/control-center'
    | '/_authenticated/control-center/live'
    | '/_authenticated/control-center/observers'
    | '/_authenticated/control-center/public'
    | '/_authenticated/control-center/reports'
    | '/_authenticated/control-center/settings'
    | '/_authenticated/control-center/training'
    | '/_authenticated/control-center/users'
    | '/_authenticated/control-center/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LiveRoute: typeof LiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/control-center': {
      id: '/_authenticated/control-center'
      path: '/control-center'
      fullPath: '/control-center'
      preLoaderRoute: typeof AuthenticatedControlCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/control-center/': {
      id: '/_authenticated/control-center/'
      path: '/'
      fullPath: '/control-center/'
      preLoaderRoute: typeof AuthenticatedControlCenterIndexRouteImport
      parentRoute: typeof AuthenticatedControlCenterRoute
    }
    '/_authenticated/control-center/live': {
      id: '/_authenticated/control-center/live'
      path: '/live'
      fullPath: '/control-center/live'
      preLoaderRoute: typeof AuthenticatedControlCenterLiveRouteImport
      parentRoute: typeof AuthenticatedControlCenterRoute
    }
    '/_authenticated/control-center/observers': {
      id: '/_authenticated/control-center/observers'
      path: '/observers'
      fullPath: '/control-center/observers'
      preLoaderRoute: typeof AuthenticatedControlCenterObserversRouteImport
      parentRoute: typeof AuthenticatedControlCenterRoute
    }
    '/_authenticated/control-center/public': {
      id: '/_authenticated/control-center/public'
      path: '/public'
      fullPath: '/control-center/public'
      preLoaderRoute: typeof AuthenticatedControlCenterPublicRouteImport
      parentRoute: typeof AuthenticatedControlCenterRoute
    }
    '/_authenticated/control-center/reports': {
      id: '/_authenticated/control-center/reports'
      path: '/reports'
      fullPath: '/control-center/reports'
      preLoaderRoute: typeof AuthenticatedControlCenterReportsRouteImport
      parentRoute: typeof AuthenticatedControlCenterRoute
    }
    '/_authenticated/control-center/settings': {
      id: '/_authenticated/control-center/settings'
      path: '/settings'
      fullPath: '/control-center/settings'
      preLoaderRoute: typeof AuthenticatedControlCenterSettingsRouteImport
      parentRoute: typeof AuthenticatedControlCenterRoute
    }
    '/_authenticated/control-center/training': {
      id: '/_authenticated/control-center/training'
      path: '/training'
      fullPath: '/control-center/training'
      preLoaderRoute: typeof AuthenticatedControlCenterTrainingRouteImport
      parentRoute: typeof AuthenticatedControlCenterRoute
    }
    '/_authenticated/control-center/users': {
      id: '/_authenticated/control-center/users'
      path: '/users'
      fullPath: '/control-center/users'
      preLoaderRoute: typeof AuthenticatedControlCenterUsersRouteImport
      parentRoute: typeof AuthenticatedControlCenterRoute
    }
  }
}

interface AuthenticatedControlCenterRouteChildren {
  AuthenticatedControlCenterLiveRoute: typeof AuthenticatedControlCenterLiveRoute
  AuthenticatedControlCenterObserversRoute: typeof AuthenticatedControlCenterObserversRoute
  AuthenticatedControlCenterPublicRoute: typeof AuthenticatedControlCenterPublicRoute
  AuthenticatedControlCenterReportsRoute: typeof AuthenticatedControlCenterReportsRoute
  AuthenticatedControlCenterSettingsRoute: typeof AuthenticatedControlCenterSettingsRoute
  AuthenticatedControlCenterTrainingRoute: typeof AuthenticatedControlCenterTrainingRoute
  AuthenticatedControlCenterUsersRoute: typeof AuthenticatedControlCenterUsersRoute
  AuthenticatedControlCenterIndexRoute: typeof AuthenticatedControlCenterIndexRoute
}

const AuthenticatedControlCenterRouteChildren: AuthenticatedControlCenterRouteChildren =
  {
    AuthenticatedControlCenterLiveRoute: AuthenticatedControlCenterLiveRoute,
    AuthenticatedControlCenterObserversRoute:
      AuthenticatedControlCenterObserversRoute,
    AuthenticatedControlCenterPublicRoute:
      AuthenticatedControlCenterPublicRoute,
    AuthenticatedControlCenterReportsRoute:
      AuthenticatedControlCenterReportsRoute,
    AuthenticatedControlCenterSettingsRoute:
      AuthenticatedControlCenterSettingsRoute,
    AuthenticatedControlCenterTrainingRoute:
      AuthenticatedControlCenterTrainingRoute,
    AuthenticatedControlCenterUsersRoute: AuthenticatedControlCenterUsersRoute,
    AuthenticatedControlCenterIndexRoute: AuthenticatedControlCenterIndexRoute,
  }

const AuthenticatedControlCenterRouteWithChildren =
  AuthenticatedControlCenterRoute._addFileChildren(
    AuthenticatedControlCenterRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedControlCenterRoute: typeof AuthenticatedControlCenterRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedControlCenterRoute: AuthenticatedControlCenterRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  HowItWorksRoute: HowItWorksRoute,
  LiveRoute: LiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
