-- ============================================================================
-- DIGITs Nigeria Election Watch — DIGEO curriculum seed
-- Six published modules with multi-question assessments. Re-runnable: content
-- is upserted on module_number.
-- ============================================================================

INSERT INTO public.digeo_training_modules
  (module_number, title, description, category, duration_minutes, pass_mark, is_published, key_points, content_markdown, quiz_data)
VALUES
(
  1,
  'The Electoral Act 2022 and your rights as an observer',
  'What the law lets you do at a polling unit, what it forbids, and how to assert access without confrontation.',
  'Legal framework', 18, 70, true,
  '["Accreditation must be visible at all times","Observe and record — never direct, assist or interfere","You may not be lawfully removed for observing peacefully","Escalate obstruction to the Command Center, not to argument"]'::jsonb,
  E'## Why the law matters before the camera does\n\nAn observer whose legal footing is clear does not argue. You are present under the Electoral Act 2022, which recognises accredited observation of accreditation, voting, counting, and the declaration of results at the polling unit.\n\n### What you may do\n- Stand where you can see the process without joining the queue or the counting table.\n- Record video and photographs of the process from an unobtrusive distance.\n- Copy publicly posted results (Form EC8A) once they are pasted at the polling unit.\n- Ask the Presiding Officer procedural questions during natural pauses.\n\n### What you must never do\n- Handle ballot papers, the BVAS, result sheets, or any election material.\n- Assist, coach, or influence a voter — including "helping" an elderly voter.\n- Wear, carry, or display party colours, logos, or slogans.\n- Argue with officials, agents, or security. Record, log, escalate.\n\n### If you are obstructed\n1. Stay calm and restate your accreditation once, showing your badge.\n2. Note the time, the name and rank of the person obstructing you, and the polling unit code.\n3. File an incident report with severity **high** and, if it is safe, capture an i-Witness clip.\n4. The Command Center escalates to INEC and to the observer coordinator — that is their job, not yours.\n\n> Your safety outranks any single observation. Withdraw from any situation turning violent and report from a safe distance.',
  '[
    {"question":"A Presiding Officer tells you observers are not allowed to record anything. What is the correct response?","options":["Argue that the law is on your side until they relent","Stop observing and leave the polling unit","Restate your accreditation once, log the obstruction, and escalate to the Command Center","Record covertly without telling anyone"],"correctIndex":2,"explanation":"Observers de-escalate and escalate through the Command Center. Arguing risks your accreditation and your safety."},
    {"question":"An elderly voter asks you to help her mark her ballot. You should:","options":["Help her — it is a courtesy","Politely decline and refer her to the Presiding Officer","Mark it for her but photograph it as proof","Ask a party agent to help her"],"correctIndex":1,"explanation":"Assisting a voter compromises your neutrality. Assistance is the Presiding Officer''s statutory duty."},
    {"question":"Which of these is NOT part of an observer''s mandate?","options":["Observing accreditation and voting","Recording the counting process","Copying the publicly posted Form EC8A","Handling the BVAS to check its battery level"],"correctIndex":3,"explanation":"Observers never touch election materials, including the BVAS."},
    {"question":"You notice a party agent wearing full party regalia inside the polling unit. What do you do?","options":["Remove them yourself","Log it as an incident with evidence and continue observing","Ignore it — agents are allowed to wear anything","Post about it on social media immediately"],"correctIndex":1,"explanation":"Document and escalate. Enforcement belongs to INEC and security agencies."}
  ]'::jsonb
),
(
  2,
  'BVAS, accreditation and the zero-print check',
  'The bimodal accreditation chain end to end, plus the checks that catch a manipulated machine.',
  'Technical observation', 22, 70, true,
  '["Verify the zero-print certificate before accreditation opens","Watch for fingerprint-then-facial fallback order","Manual accreditation is an exception, not a routine","Log every BVAS failure with timestamps"]'::jsonb,
  E'## The accreditation chain\n\nThe Bimodal Voter Accreditation System (BVAS) authenticates a voter by fingerprint, falling back to facial recognition. Accreditation and voting happen in one continuous visit.\n\n### Before accreditation opens\n1. Confirm the BVAS is switched on in your presence.\n2. **Verify the zero-print certificate** — the machine must show zero accredited voters before the first voter is processed. Photograph it.\n3. Note the machine''s serial number and the polling unit code together in one frame.\n\n### During accreditation\n- The voter presents their PVC; the officer scans it and captures a fingerprint.\n- If the fingerprint fails, facial capture is attempted. Both failing means the voter cannot be accredited by BVAS.\n- Watch the count on screen versus the physical queue. A count climbing faster than people are processed is a red flag.\n\n### Failure modes worth reporting immediately\n| Symptom | Severity | What to capture |\n| --- | --- | --- |\n| BVAS will not boot | High | Time, serial, officer response |\n| Battery dies with no backup | High | Time, whether accreditation paused |\n| Officer accredits without a scan | Critical | Continuous clip, count on screen |\n| Count jumps while queue is static | Critical | Screen and queue in one frame |\n\n### Manual accreditation\nManual (incident-form) accreditation is an exception. Record how many voters were processed manually and whether the Presiding Officer documented each one. Routine manual accreditation is a serious irregularity.',
  '[
    {"question":"When must the BVAS zero-print certificate be verified?","options":["At the end of voting","Before the first voter is accredited","During collation","Only if an agent requests it"],"correctIndex":1,"explanation":"The zero-print proves the machine started from zero. It is worthless after accreditation begins."},
    {"question":"The BVAS accreditation count rises by 30 while only 4 people have approached the desk. This is:","options":["Normal batching behaviour","A display glitch to ignore","A critical irregularity to record and escalate immediately","Something only INEC can see"],"correctIndex":2,"explanation":"A count decoupled from the physical queue is a hallmark of accreditation manipulation."},
    {"question":"BVAS authenticates a voter using:","options":["Fingerprint only","Facial recognition only","Fingerprint with facial recognition as fallback","A PIN issued at registration"],"correctIndex":2,"explanation":"Bimodal means two modes: fingerprint first, facial capture as fallback."},
    {"question":"Routine manual accreditation of many voters should be treated as:","options":["Standard practice on busy days","A serious irregularity requiring documentation","The observer''s decision to approve","Irrelevant to the result"],"correctIndex":1,"explanation":"Manual accreditation is an exception; at scale it defeats the purpose of biometric verification."}
  ]'::jsonb
),
(
  3,
  'Counting, Form EC8A and the IReV upload',
  'How a polling unit result is produced, signed, posted and uploaded — and where results go missing.',
  'Result transparency', 25, 70, true,
  '["Sorting and counting must be public and audible","Every agent present is entitled to sign EC8A","Photograph EC8A in full, flat, and legible","Confirm the IReV upload before you leave"]'::jsonb,
  E'## From ballot box to result sheet\n\n### Sorting and counting\nBallots are emptied in full view, sorted by party, and counted aloud. Rejected ballots are announced with the reason. If counting moves out of public view, that alone is reportable.\n\n### Form EC8A — the polling unit result\nEC8A is the authoritative polling unit record. Check that it carries:\n- Polling unit name **and** code.\n- Registered voters, accredited voters, valid votes, rejected ballots, total votes cast.\n- Party-by-party scores in both figures and words where required.\n- Signatures of the Presiding Officer and every party agent present.\n\n### The three arithmetic checks\n1. Accredited voters **≤** registered voters.\n2. Total votes cast **≤** accredited voters.\n3. Valid votes **+** rejected ballots **=** total votes cast.\n\nAny failure is a hard irregularity. Record the exact figures — not your impression of them.\n\n### Photographing EC8A\nHold the sheet flat, fill the frame, avoid glare, and take a second frame close on the figures block. An unreadable EC8A photo is not evidence.\n\n### The upload\nThe Presiding Officer uploads EC8A to the INEC Result Viewing portal (IReV) from the polling unit. Stay until you have seen the upload attempt and can state whether it succeeded, failed, or was deferred. A result that never reaches IReV is where a clean count becomes a disputed one.',
  '[
    {"question":"Valid votes 210, rejected ballots 12, total votes cast recorded as 230. This means:","options":["The sheet is consistent","The arithmetic fails and must be reported","Rejected ballots are excluded from the total","Only INEC can judge this"],"correctIndex":1,"explanation":"210 + 12 = 222, not 230. Valid plus rejected must equal total votes cast."},
    {"question":"Which figure can never legitimately exceed the number of accredited voters?","options":["Registered voters","Total votes cast","Party agents present","Rejected ballots from the previous election"],"correctIndex":1,"explanation":"Nobody can vote without being accredited, so votes cast cannot exceed accreditation."},
    {"question":"Party agents refuse to sign EC8A. The correct observer action is:","options":["Sign it yourself as a witness","Record which agents declined and why, then report it","Insist that counting restarts","Leave immediately"],"correctIndex":1,"explanation":"Observers never sign result sheets. Document refusals and the stated reasons."},
    {"question":"Before leaving the polling unit you should confirm:","options":["That the EC8A upload to IReV was attempted and its outcome","That your own tally matches the winner you expected","That agents have gone home","Nothing — your job ends at counting"],"correctIndex":0,"explanation":"The upload is the point where results most often disappear. Witness it."}
  ]'::jsonb
),
(
  4,
  'Capturing evidence that stands up',
  'Framing, timestamps, geolocation, chain of custody and the two-minute discipline of i-Witness clips.',
  'Evidence and reporting', 20, 70, true,
  '["Establish place before you record action","Two minutes forces you to capture the decisive moment","Real-time capture only — no gallery uploads","Never edit, crop, or filter evidence"]'::jsonb,
  E'## Evidence is a claim about place, time and event\n\nA clip that proves *something happened* but not *where or when* is close to useless in a dispute.\n\n### The three-shot pattern\n1. **Establish** — polling unit signage or code board, 3-5 seconds.\n2. **Wide** — the whole scene so the event cannot be argued out of context.\n3. **Close** — the specific act: the hand, the sheet, the screen, the count.\n\n### Why DIGITs caps clips at two minutes\nLong clips bury the decisive moment and fail on weak networks. Two minutes forces you to decide what actually matters. Record several short clips instead of one long one.\n\n### Real-time capture only\nThe recorder captures from your camera at the moment of the event. You cannot attach a file from your gallery. This is deliberate: a file from storage carries no proof of when or where it was made, and one recycled video can discredit an entire observation network.\n\n### What DIGITs attaches automatically\n- Device timestamp at capture.\n- GPS coordinates and accuracy radius.\n- Your verified name and NIN.\n- A content hash so any later alteration is detectable.\n\n### Handling and retention\nEvidence uploads to private cloud storage the Command Center can access. It disappears from your in-app history after 24 hours — save a copy to your own device at capture time if you want to keep it. Never edit, crop, brighten, or add captions to evidence; annotate in the description field instead.',
  '[
    {"question":"Why does the i-Witness recorder refuse uploads from your device gallery?","options":["To save bandwidth","Because a stored file cannot prove when or where it was captured","Because galleries are private","To limit file sizes"],"correctIndex":1,"explanation":"Real-time capture is what binds the evidence to a place and time."},
    {"question":"The strongest evidence sequence is:","options":["One continuous ten-minute clip","Establishing shot, wide shot, then close shot","A close-up only","A photo of the crowd afterwards"],"correctIndex":1,"explanation":"Establish, wide, close proves place, context and act in turn."},
    {"question":"You want to keep a clip you filed today. You should:","options":["Rely on your in-app history","Save it to your device when prompted after capture","Email it to yourself","Re-record it tomorrow"],"correctIndex":1,"explanation":"In-app history clears after 24 hours; the save-to-device prompt is your only local copy."},
    {"question":"Brightening a dark evidence clip before submitting is:","options":["Recommended for clarity","Acceptable if you mention it","Never acceptable — it breaks the chain of custody","Required by the platform"],"correctIndex":2,"explanation":"Any alteration invites the accusation of tampering. Describe conditions in text instead."}
  ]'::jsonb
),
(
  5,
  'Neutrality, conduct and personal safety',
  'Holding the line on impartiality, refusing inducement, and getting out of danger without losing the record.',
  'Conduct and safety', 16, 70, true,
  '["Neutrality is visible behaviour, not private intention","Declare and decline every inducement","Safety first: withdraw, then report","Use the panic beacon before the situation closes in"]'::jsonb,
  E'## Neutrality is something people can see\n\nYour credibility is the network''s credibility. It is judged from the outside, on behaviour.\n\n### Conduct commitments\n- No party colours, logos, slogans, gestures, or campaign talk — including on your personal social media on election day.\n- No comment to journalists on who is winning. Refer them to the Command Center.\n- No accepting food, transport money, airtime, or gifts from any party, agent, or candidate.\n- No predictions, no arguments, no celebration.\n\n### If you are offered an inducement\n1. Decline clearly and without insult.\n2. Log an incident report of type **vote_buying** including who, when, and what was offered.\n3. Capture evidence only if doing so is safe. Never bait or provoke to obtain evidence.\n\n### Personal safety protocol\n| Situation | Action |\n| --- | --- |\n| Rising tension, raised voices | Move to the perimeter, keep recording wide |\n| Physical violence begins | Stop recording, leave, report from safety |\n| You are personally threatened | Trigger the panic beacon, withdraw, call your coordinator |\n| Materials are seized or destroyed | Withdraw first, then file a critical incident |\n\nThe panic beacon sends your live coordinates and identity to the Command Center. Use it early — a beacon you triggered and did not need costs nothing.\n\n> No observation is worth an injury. A withdrawn observer who files a clear report from safety has done the job correctly.',
  '[
    {"question":"A candidate''s agent offers you transport money because you look tired. You should:","options":["Accept it — it is not a bribe","Decline clearly and file a vote_buying incident report","Accept and donate it later","Ignore the offer entirely and say nothing"],"correctIndex":1,"explanation":"Accepting anything of value destroys your neutrality; the offer itself is reportable."},
    {"question":"Violence breaks out at the polling unit. Your first action is:","options":["Keep recording from the middle of it","Withdraw to safety, then report","Intervene to calm people down","Wait for security to arrive before moving"],"correctIndex":1,"explanation":"Safety outranks the record. Withdraw first, then report from a safe distance."},
    {"question":"A journalist asks who you think is winning. You should:","options":["Give your honest reading","Refer them to the Command Center and decline to comment","Share your tally sheet","Answer off the record"],"correctIndex":1,"explanation":"Observers do not characterise outcomes. All external comment goes through the Command Center."},
    {"question":"The panic beacon should be used:","options":["Only after you are physically harmed","Early, as soon as you feel personally threatened","Never — it is for coordinators","Only if your phone has full signal"],"correctIndex":1,"explanation":"Early activation is the point: it gives the Command Center time to respond."}
  ]'::jsonb
),
(
  6,
  'Streaming live from your polling unit',
  'Going live on the DIGITs grid: consent, framing, connectivity, battery discipline and Command Center hand-off.',
  'Live broadcast', 20, 70, true,
  '["Never frame a marked ballot or a voter''s choice","Lock your framing — the grid cannot use a swinging camera","Battery and data are part of the observation plan","An operator, not you, decides what goes public"]'::jsonb,
  E'## Going live is a public act\n\nYour stream may be placed on a public grid watched by thousands. A Command Center operator chooses which feeds go public and into which of the six tiles — you never publish directly.\n\n### Ballot secrecy is absolute\nNever frame a ballot being marked, a voter''s hands at the booth, or anything that reveals how an identifiable person voted. Frame the process, not the choice. When in doubt, raise the camera.\n\n### Framing for the grid\n- Landscape, braced or propped — a swinging camera is unusable at tile size.\n- Fill the frame with the process: the desk, the queue, the counting table.\n- Keep the polling unit code visible in your establishing shot so operators can label your tile.\n- Test that ambient audio is intelligible; commentary from you is not required.\n\n### Connectivity and power\n- Start the stream at the lowest quality that stays stable; the platform adapts upward automatically.\n- Expect congested networks at peak accreditation. A stable 480p feed beats a stuttering 1080p feed.\n- Arrive with a full charge plus a power bank. Streaming is the heaviest thing your phone will do all day.\n- If you drop, reconnect rather than starting a new stream so your tile stays continuous.\n\n### Hand-off discipline\nAnnounce nothing on air. If something critical happens, keep streaming and file a parallel incident report so the Command Center can act while the feed continues.',
  '[
    {"question":"A voter is marking their ballot two metres from your camera. You should:","options":["Zoom in — it proves voting is happening","Raise or turn the camera so the ballot is not visible","Keep filming but blur it later","Ask them who they voted for"],"correctIndex":1,"explanation":"Ballot secrecy is absolute. Frame the process, never the choice."},
    {"question":"Your network is congested at peak accreditation. The right move is:","options":["Force 1080p and accept stuttering","Stream at a lower stable quality and let the platform adapt upward","Stop streaming until the network clears","Switch to a personal social media app"],"correctIndex":1,"explanation":"A stable lower-quality feed is usable on the grid; a stuttering one is not."},
    {"question":"Who decides whether your feed appears on the public grid?","options":["You, when you press go live","A Command Center operator","The most-watched observer","Any authenticated viewer"],"correctIndex":1,"explanation":"Operators curate the public tiles; observers publish into the Command Center only."},
    {"question":"Something critical happens while you are live. You should:","options":["Stop the stream to file a report","Keep streaming and file a parallel incident report","Narrate your opinion on air","Wait until the end of the day"],"correctIndex":1,"explanation":"The feed keeps the record; the incident report is what makes the Command Center act."}
  ]'::jsonb
)
ON CONFLICT (module_number) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  duration_minutes = EXCLUDED.duration_minutes,
  pass_mark = EXCLUDED.pass_mark,
  is_published = EXCLUDED.is_published,
  key_points = EXCLUDED.key_points,
  content_markdown = EXCLUDED.content_markdown,
  quiz_data = EXCLUDED.quiz_data,
  updated_at = now();
